export default {
  app: { title: 'NIT OA system', logout: 'Log out', language: 'Language', role: 'Role', changePassword: 'Change password' },
  nav: { home: 'Home', employees: 'People', internalEmployees: 'Internal people', externalEmployees: 'External people', contracts: 'Contracts', internalContracts: 'Internal contracts', externalContracts: 'External contracts', externalContractsNew: 'New external contract', externalPartners: 'Contracted companies', documentManagement: 'Documents', purchaseOrders: 'Purchase orders', quotations: 'Quotations', invoices: 'Invoices', documentHistory: 'Document history', documentLibrary: 'All documents', approvals: 'Approvals', contractApprovals: 'Contract approvals', reimbursementApprovals: 'Expense approvals', reimbursements: 'Expenses', expenseSettlement: 'Expenses & settlement', reimbursementClaims: 'Expense claims', salaryDetails: 'Salary details', monthlySettlement: 'Monthly settlement', subcontracting: 'Subcontracting', subcontractingNotice: 'Company notice', subcontractingQuotations: 'Partner quotations', subcontractingInvoices: 'Partner invoices', subcontractingPersonnel: 'Entry personnel', attendance: 'Attendance', attendanceSummary: 'Attendance list', attendanceRequests: 'Requests', attendanceApprovals: 'Attendance approvals', attendanceSettings: 'Calendar settings', projects: 'Projects', settings: 'Settings', mailSettings: 'Mail settings', permissionManagement: 'Permission management' },
  login: { title: 'Sign in', email: 'Email', password: 'Password', submit: 'Sign in', forgot: 'Reset password', sso: 'Teams SSO', eyebrow: 'NIT DX Portal', headline: 'Make work smoother.', headlineAccent: 'NIT OA system', subhead: 'People, contracts, and projects in one place, with less searching and fewer handoffs.', panelEyebrow: 'Staff entrance', panelHint: 'Open the information you need and move daily work forward quickly.', capabilities: { people: 'Clear people records', contracts: 'Quick contract and payroll checks', projects: 'Smoother project assignment' }, forceResetTitle: 'Reset password on first sign-in', forceResetHint: 'You are using the initial password. Please set a new password first.', changePasswordTitle: 'Change password', changePasswordHint: 'Enter your current password and set a new one.', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm new password' },
  common: { search: 'Search', create: 'Create', edit: 'Edit', delete: 'Delete', save: 'Save', cancel: 'Cancel', confirm: 'Confirm', import: 'Import', upload: 'Upload', download: 'Download', actions: 'Actions', refresh: 'Refresh', analyze: 'Analyze', recommend: 'Recommend', assign: 'Assign', send: 'Send', required: 'Required', success: 'Success', failed: 'Failed', columns: 'Columns', detail: 'Detail', yes: 'Yes', no: 'No', confirmDelete: 'Delete this record?' },
  validation: { required: 'This field is required', email: 'Enter a valid email address', employeeName: 'Name may contain Japanese, kanji, or English only', jpPhone: 'Enter a valid Japanese phone number', passwordMismatch: 'The new passwords do not match' },
  fields: {
    id: 'ID', fullName: 'Name', nameKana: 'Japanese kana', email: 'Email', platformEmail: 'Platform account', phone: 'Phone', birthDate: 'Birth date', age: 'Age', graduationStatus: 'Graduation status', residence: 'Residence', nearestStation: 'Nearest station', nationality: 'Nationality', employeeType: 'Employee type', languages: 'Languages', certifications: 'Certifications', technicalExperience: 'Technical experience', itYears: 'IT years', talentCategory: 'Talent category', skills: 'Skills',
    title: 'Title', employee: 'Employee', contractType: 'Contract type', vendorCompany: 'Vendor company', startDate: 'Start date', endDate: 'End date',
    baseSalary: 'Base salary', allowanceTotal: 'Allowance total', baseUnitPriceLow: 'Base unit low', baseUnitPriceHigh: 'Base unit high', salaryTotalMonthly: 'Monthly total', duty: 'Duty',
    allowances: 'Allowances', amount: 'Amount', pdfFile: 'PDF file', parsedText: 'Parsed text', yearMonth: 'Month', hoursRange: 'Hours band', monthlyHours: 'Monthly hours', estimatedSalary: 'Calculated pay', payableSalary: 'Payable salary', actualSalary: 'Current month pay', reimbursementAmount: 'Expense reimbursement', grossPaymentTotal: 'Total payments', deductionTotal: 'Total deductions', taxablePaymentTotal: 'Taxable pay', socialInsuranceTotal: 'Social insurance total', estimatedAnnualSalary: 'Estimated annual salary', locked: 'Locked', pension: 'Pension', residentTax: 'Resident tax', insuranceFee: 'Insurance fee', note: 'Note',
    clientCompany: 'Client company', projectName: 'Project name', description: 'Description', requiredSkills: 'Required skills', workplace: 'Workplace', nationalityRequirement: 'Nationality requirement', duration: 'Duration', headcount: 'Headcount', assignedEmployees: 'Assigned people', unitPrice: 'Unit price', createdAt: 'Created at', subject: 'Email subject', body: 'Email body', attachmentText: 'Attachment text',
    source: 'Source', confidence: 'Confidence', remoteType: 'Remote type', station: 'Station', aiError: 'AI error', rawEmail: 'Raw email', attributes: 'Attributes'
  },
  home: { profile: 'Profile', contracts: 'Contracts', salary: 'Salary', projects: 'Assigned projects', noData: 'No data', contactAdmin: 'Metadata is incomplete. Please contact an administrator.', welcome: 'Welcome, ', heroCopy: 'Contracts, salary, and assigned work are gathered in one portal.', partnerHero: 'A subcontracting portal for partners to submit documents, entry personnel, and download fixed materials.', salaryDetail: 'Salary detail', salarySummary: 'Salary summary', paymentItems: 'Payments', deductionItems: 'Deductions', salaryCalculationNote: 'Salary is calculated from attendance, project assignment, approved reimbursements, and deduction settings. Locked months are not recalculated automatically.', downloadPayslip: 'Download payslip', downloadAnnual: 'Download annual PDF', assistantGreeting: 'Ask about company information and internal procedures.', assistantOnline: 'Online', assistantOffline: 'Not configured', assistantOfflineHint: 'The AI assistant is not configured. Please ask an administrator to set the Dify API Base and API Key.', assistantError: 'The AI assistant returned an error.', assistantPlaceholder: 'Ask a question', assistantNewChat: 'New conversation', assistantSources: 'Sources', assistantSuggestionPeople: 'Tell me about onboarding and offboarding', assistantSuggestionExpense: 'Tell me how expense claims work', assistantSuggestionContract: 'Tell me how to submit contract documents' },
  employees: { importHelp: 'Supports tables and Japanese resume workbook format', employmentInfo: 'Employment info', defaultPassword: "New platform accounts are generated as surname_given{'@'}nit-g.co.jp. The initial password comes from DEFAULT_EMPLOYEE_PASSWORD and must be reset on first sign-in.", resetPassword: 'Reset password', resetPasswordConfirm: 'Reset {name} to the default password?', passwordResetDone: 'Password reset: {email}' },
  contracts: { importPdf: 'Import PDF contract', manualCreate: 'Add contract manually', manualEdit: 'Edit contract metadata', addAllowance: 'Add allowance', hoursRangeInvalid: 'Enter the hours range as 140-180', due: 'Due in 30 days', sendReminders: 'Send reminders', longTerm: 'Long term', batchNote: 'Expiration reminders are sent automatically by the daily 09:00 batch to HR_REMINDER_EMAIL.', detailTitle: 'Contract detail', salaryDetail: 'Salary and unit rate', contractInfo: 'Contract info', salaryManagement: 'Salary details' },
  external: {
    partners: 'Contracted companies', contracts: 'New contracts', documents: 'Documents', approvals: 'Approvals', settlement: 'Monthly settlement',
    newPartner: 'Add company', newContract: 'New contract', uploadUpstream: 'Upload upstream contract', companyName: 'Company name', companyKana: 'Company kana', partnerType: 'Direction', partnerAccount: 'Partner account', temporaryPassword: 'Temporary password', sendPartnerAccount: 'Send account mail', sendPartnerAccountConfirm: 'Reset the temporary password and send it to the contact email?', accountMailSent: 'Account mail sent', accountMailMissingEmail: 'Please enter a contact email first',
    contractedAt: 'Contracted date', contractedSuccess: 'Contracted', contractEndDate: 'Contract end date', terminated: 'Terminated', contractActive: 'Active contract', contactName: 'Contact', relatedPeople: 'Related people', address: 'Address', direction: 'Direction', status: 'Status', fixedFiles: 'Fixed files', downloadFixedPack: 'Download fixed pack', useExistingCompany: 'Use contracted company',
    generateDocuments: 'Generate purchase order / quotation', generatePurchaseOrder: 'Generate purchase order', generateQuotation: 'Generate quotation', invoiceFromQuotation: 'Generate invoice from quotation',
    selectQuotation: 'Select quotation', approvedQuotation: 'Approved partner quotation', approvedQuotationRequired: 'Select an approved partner quotation first', generateInvoice: 'Generate invoice', targetMonth: 'Target month', issueDate: 'Issue date', dueDate: 'Due date',
    itemName: 'Item', quantity: 'Quantity', unitPrice: 'Unit price', baseHours: 'Base hours', documentType: 'Document type', documentNo: 'Document no.',
    total: 'Total', invoiceTotal: 'Invoice total', purchaseTotal: 'Partner invoice total', salaryTotal: 'Actual salary total', netIncome: 'Net income',
    downstreamOnly: 'Purchase orders are only available for downstream or both companies',
    upstreamOnly: 'Quotations and invoices are only available for upstream or both companies',
    documentRuleHint: 'Document rules: downstream can only create purchase orders; upstream can create quotations and invoices; both can create all documents.',
    invoiceDetails: 'Invoice receipt details', purchaseDetails: 'Partner invoice payment details', received: 'Received', receivedAmount: 'Received amount', paid: 'Paid', paidAmount: 'Paid amount', effectiveAmount: 'Counted amount',
    pendingApprovals: 'Pending approvals', approvalStatus: 'Approval status', approve: 'Approve', reject: 'Reject', withdraw: 'Withdraw',
    documentTypes: { purchase_order: 'Purchase order', quotation: 'Quotation', invoice: 'Invoice', uploaded_contract: 'Uploaded contract', partner_quotation: 'Partner quotation', partner_invoice: 'Partner invoice' }
  },
  subcontracting: { partnerQuotation: 'Partner quotation', submitQuotation: 'Upload quotation', quotationFile: 'Quotation file', approvalStatus: 'Approval status', entryPersonnel: 'Entry personnel', assignmentMonth: 'Assignment month', submitPersonnel: 'Submit personnel', companyNotice: 'Company notice / declaration' },
  reimbursements: { expenseType: 'Expense type', period: 'Expense period', periodStart: 'Start month', periodEnd: 'End month', payMonth: 'Payment month', files: 'Receipts/files', traffic: 'Transportation', businessTrip: 'Business trip', teamBuilding: 'Team event', other: 'Other' },
  approvals: { contractApprovals: 'Contract approvals', reimbursementApprovals: 'Expense approvals', attendanceApprovals: 'Attendance approvals', rejectTitle: 'Reject', rejectPrompt: 'Enter a rejection reason', rejectRequired: 'A rejection reason is required' },
  permissions: { hint: 'This only controls frontend menu and route visibility. API access remains protected by the existing role permissions.', role: 'Target role' },
  projects: { analyzeEmail: 'Analyze email', pollMailbox: 'Read mailbox', recommendations: 'Candidate recommendations', reasons: 'Reasons', score: 'Score', detailTitle: 'Project detail', aiResult: 'AI extraction result', assignmentFull: 'The project headcount is full.', reassign: 'Reassign', unassign: 'Unassign', unassignConfirm: 'Unassign this employee from the project?' }
  ,
  settings: {
    mail: 'Mailbox settings', provider: 'Provider', disabled: 'Disabled', gmail: 'Gmail App Password', generic: 'Generic IMAP+SMTP', smtpOnly: 'SMTP only',
    enabled: 'Enabled', imapEnabled: 'Receive mail', smtpEnabled: 'Send mail', imapHost: 'IMAP host', imapPort: 'IMAP port', imapUsername: 'IMAP account', imapPassword: 'IMAP password', imapFolder: 'Mailbox folder',
    smtpHost: 'SMTP host', smtpPort: 'SMTP port', smtpUsername: 'SMTP account', smtpPassword: 'SMTP password', smtpFrom: 'From address', smtpTls: 'STARTTLS', pollInterval: 'Polling interval seconds',
    hasPassword: 'Saved password', testImap: 'Test receiving', testSmtp: 'Test sending'
  }
}
